name: Stale issue/pr handler

on:
  workflow_dispatch:
  schedule:
    - cron: '25 4 * * *'

env:
  SLACK_NOTIFY: false

permissions:
  issues: write
  pull-requests: write

jobs:
  handle-stale-entries:
    name: Handle stale Issues & PRs
    runs-on: ubuntu-latest
    steps:
      - name: Handle state Issues & PRs
        uses: actions/stale@v6
        id: stale
        with:
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 5 days with no activity.'
          days-before-issue-stale: 30
          days-before-issue-close: 5
          stale-issue-label: 'state: stale'
          close-issue-label: 'resolution closed'
          exempt-issue-labels: 'state: blocked,state: keep'
          stale-pr-message: 'This PR is stale because it has been open 45 days with no activity. Remove stale label or comment or this will be closed in 10 days.'
          close-pr-message: 'This PR was closed because it has been stalled for 10 days with no activity.'
          days-before-pr-stale: 45
          days-before-pr-close: 10
          stale-pr-label: 'state: stale'
          close-pr-label: 'resolution: closed'
          exempt-pr-labels: 'state: blocked,state: keep'

  slack-workflow-status:
    if: always()
    name: Slack Post Workflow Notification
    needs:
      - handle-stale-entries
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notifications
        if: ${{ env.SLACK_NOTIFY == 'true' && github.event_name == 'push' }}
        uses: Gamesight/slack-workflow-status@v1.1.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          include_jobs: on-failure
          include_commit_message: true
